### PR TITLE
Fix yt-dlp invocation for unix systems.

### PR DESCRIPTION
**Pull request by ghost**
I have no clue how the original worked on windows. It looks like quoting is handled differently there. (Edited version not tested on windows)

Also replaced legacy Runtime#exec calls with ProcessBuilder, which are (to my knowledge) not deprecated. Additionally, there should be less attack surface for injections now (although I might have spotted some elsewhere, not sure though)

### CODE REVIEW

**Review by CodingBaum — COMMENTED** [review]
I will merge this after testing it for windows. Codewise it looks clean.

**Comment by CodingBaum** [comment]
The general call to yt-dlp seems to work. However, when trying to get a song from youtube it is unable to retrieve any information about it, other then the song itself. For SoundCloud it works fine. Is this the same behaviour as on linux?

**Comment by ghost** [comment]
This looks like a problem from [these lines](https://github.com/htl9141/OpenSoundQueue/blob/4f2fbfa3fb235374d70fe1da4690083316db032d/backend/src/main/java/com/example/backend/streaming/ytdlp/YtDlpService.java#L55):

```java
Process process = new ProcessBuilder("yt-dlp", "--dump-single-json", song.getLink())
    .redirectErrorStream(true) // [1]
    .start()
```
Line [1] redirects the errors and warnings from yt-dlp to the same output. (See example at the bottom). Errors and warnings are invalid JSON, thus jackson throws a JSONParseException, which is (currently) **not** caught. In consequence, the outer while loop does not continue and OSQ is unable to fetch data.

Example output from me manually running the command:

```bash
user@OSQ:~$ yt-dlp --version
2024.05.27
user@OSQ:~$ yt-dlp --dump-single-json https://www.youtube.com/watch?v=Sv6dMFF_yts
WARNING: [youtube] Sv6dMFF_yts: nsig extraction failed: You may experience throttling for some formats
         n = -k3VlrA1mUPFSx7- ; player = https://www.youtube.com/s/player/d2e656ee/player_ias.vflset/en_US/base.js
WARNING: [youtube] Sv6dMFF_yts: nsig extraction failed: You may experience throttling for some formats
         n = w9PYkElPMxFCyqrg ; player = https://www.youtube.com/s/player/d2e656ee/player_ias.vflset/en_US/base.js
{"id": "Sv6dMFF_yts", "title": "Fun.: We Are Young ft. Janelle Mon\u00e1e [OFFICIAL VIDEO]", "formats": [ ... ]}
user@OSQ:~$
```
As you can see, the real JSON output is not the first line due to some warnings. These warning might be fixed by updating yt-dlp [^1], however I agree, a more robust parsing solution is definitely required.

It may be a good solution to print the error stream using the existing LOG class, however that might require the use of new threads, as you cannot poll output and error at the same time in a single thread (as far as I know).

If you do not want to use new threads, you can just remove the line (as in my most recent commit), which fixed the problem. yt-dlp output is then sent to OSQ's standard output. Maybe not ideal, but it works.

[^1]: Updating actually fixed the problem, however that is not a good solution

**Comment by ghost** [comment]
Please test again, if you have time

**Comment by CodingBaum** [comment]
After updating yt-dlp it works fine for me as well. There are still a lot of warning for youtube in the console but as far as functionality goes there are no problems anymore. From my side this PR is approved

**Review by CodingBaum — APPROVED** [review]

**Pull request merged**
